server:
  port: 8002
 
spring:
    application:
      name: inventory-management
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://db-mysql-lon1-75379-do-user-19481328-0.d.db.ondigitalocean.com:25060/inventory-management
        username: "inventory-management"
        password: "AVNS_b0Tij-jFmsUUCgiLkUB"
        hikari:
            initialization-fail-timeout: 0  
    sql:
        int:
          platform: mysql
          mode: always        
    jpa:
        databasePlatform: "org.hibernate.dialect.MySQLDialect"
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
